[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false  # для совместимости с enableCORS=false
runOnSave = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

